In [19]:
import pickle
import numpy as np
import pandas as pd

In [4]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [23]:
predict_input =np.array( [3,'male',21.0,0,0,7.7333,'Q'],dtype =object).reshape(1,7)

In [39]:
predict_input[:,6]

array(['Q'], dtype=object)

In [29]:
ohe_test_sex = ohe_sex.transform(predict_input[:,1].reshape(1,1))
ohe_test_sex

array([[0., 1.]])

In [40]:
ohe_test_embarked = ohe_embarked.transform(predict_input[:,6].reshape(1,1))
ohe_test_embarked

array([[0., 1., 0.]])

In [33]:
test_age = predict_input[:,2].reshape(1,1)
test_age

array([[21.0]], dtype=object)

In [41]:
df_transform = np.concatenate((predict_input[:,[0,3,4,5]],test_age,ohe_test_sex,ohe_test_embarked),axis = 1)

In [42]:
df_transform.shape

(1, 10)

In [43]:
y_pred = clf.predict(df_transform)
y_pred

array([0], dtype=int64)